# Generated by Django 5.1.4 on 2025-04-22 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0001_initial"),
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adocao",
            unique_together={("user", "pet")},
        ),
    ]
